#!/usr/bin/with-contenv bash

exec s6-setuidgid abc \
  /usr/bin/transmission-daemon \
    --config-dir "${CONFIG_PATH}" \
    --incomplete-dir "${DOWNLOADS_PATH}"/incomplete \
    --download-dir "${DOWNLOADS_PATH}"/complete \
    -c "${WATCH_PATH}" \
    -f
