#!/bin/bash
set -e  # Exit on error

IMAGE_NAME="${IMAGE_NAME}"
VERSION="${DOCKER_TAG}"
REVISION="${GIT_SHA1:0:7}"
BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

echo -e "NAME:\t\t${IMAGE_NAME}"
echo -e "VERSION:\t${VERSION}"
echo -e "REVISION:\t${REVISION}"
echo -e "BUILD_DATE:\t${BUILD_DATE}"

docker build \
  --build-arg VERSION="$VERSION" \
  --build-arg REVISION="$REVISION" \
  --build-arg BUILD_DATE="$BUILD_DATE" \
  --tag "$IMAGE_NAME" .
